# ----------------------------------
# Sparked Host Custom Docker Image
# Image: ghcr.io/sparkedhost/images:golang-121
# ----------------------------------

FROM redis:7-bookworm

LABEL       author="DevOps Team at Sparked Host" maintainer="devops@sparkedhost.com"

ENV     DEBIAN_FRONTEND noninteractive

USER container
ENV  USER=container HOME=/home/container LANG=C.UTF-8

