[global]
pid = /home/container/run/php-fpm.pid
error_log = /dev/stderr
daemonize = no
include = /etc/php/8.5/fpm/pool.d/*.conf

[www]
user = container
group = container
listen = 127.0.0.1:9999
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 5
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 3
clear_env = no
catch_workers_output = yes
php_value[session.cookie_httponly] = 1
php_value[session.cookie_secure] = 1
php_value[session.cookie_samesite] = Lax
php_value[session.save_path] = /home/container/run/php/sessions
