[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/home/container/run/supervisord.pid

[program:postgres]
command=/usr/local/bin/postgres -D /home/container/postgres_db
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:php-fpm]
command=/usr/local/bin/start-adminer
autostart=true
autorestart=true
startsecs=1
environment=ADMINER_DATABASE_PORT="%(ENV_SERVER_PORT)s"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:caddy]
command=/usr/bin/env -u ADMIN_USER -u ADMIN_PASSWORD /usr/bin/caddy run --config /home/container/run/Caddyfile
autostart=true
autorestart=true
startsecs=1
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
