[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/home/container/run/supervisord.pid

[include]
files = /etc/supervisor/conf.d/adminer.conf

[program:kvrocks]
command=/usr/bin/kvrocks -c /home/container/etc/kvrocks.conf
autostart=true
autorestart=true
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
