name: Build azul-prime-17
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - java/azul-prime/azul-prime-17/*
      - java/entrypoint.sh
      - .github/workflows/azul-prime-17.yml
jobs:
  push:
    name: "azul-prime-17"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./java
          file: ./java/azul-prime/azul-prime-17/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:azul-prime-17
