name: Build dotnet-9
on:
  push:
    branches:
      - main
    paths:
      - dotnet/dotnet-9/*
      - dotnet/entrypoint.sh
      - .github/workflows/dotnet-9.yml
jobs:
  push:
    name: "dotnet-9"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./dotnet
          file: ./dotnet/dotnet-9/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:dotnet-9
