name: Build games-unturned-preview
on:
  push:
    branches:
      - main
    paths:
      - games/unturned-preview/*
      - .github/workflows/games-unturned-preview.yml
jobs:
  push:
    name: "games-unturned-preview"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./games
          file: ./games/unturned-preview/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:games-unturned-preview