name: Build java-jre18
on:
  push:
    branches:
      - main
    paths:
      - java/java-jre18/*
      - java/entrypoint.sh
      - .github/workflows/java-jre18.yml
jobs:
  push:
    name: "java-jre18"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./java
          file: ./java/java-jre18/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:java-jre18