name: Build KVRocks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "databases/kvrocks/**/*"
      - "databases/adminer/**/*"
      - .github/workflows/kvrocks.yml

jobs:
  build:
    name: "KVRocks ${{ matrix.series }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { series: "2", release: "2.16.0" }
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./databases
      file: ./databases/kvrocks/Dockerfile
      tags: ghcr.io/sparkedhost/images:kvrocks-${{ matrix.series }}
      build_args: KVROCKS_VERSION=${{ matrix.release }}
    secrets: inherit
