name: Build mariadb-11.0
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - databases/mariadb/mariadb-11.0/*
      - databases/mariadb/entrypoint.sh
      - .github/workflows/mariadb-11.0.yml
jobs:
  push:
    name: "mariadb-11.0"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./databases/mariadb
          file: ./databases/mariadb/mariadb-11.0/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:mariadb-11.0
