name: Build MongoDB

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "databases/mongodb/**/*"
      - .github/workflows/mongodb.yml

jobs:
  build:
    name: "MongoDB ${{ matrix.series }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { series: "7", release: "7.0.43" }
          - { series: "8", release: "8.0.30" }
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./databases/mongodb
      file: ./databases/mongodb/Dockerfile
      tags: ghcr.io/sparkedhost/images:mongodb-${{ matrix.series }}
      build_args: MONGO_VERSION=${{ matrix.release }}
    secrets: inherit
