name: Build MongoDB

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "databases/mongodb/**/*"
      - .github/workflows/mongodb.yml

jobs:
  build:
    name: "MongoDB ${{ matrix.version }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 6
            image: 6.0.20
          - version: 7
            image: 7.0.16
          - version: 8
            image: 8.0.4
    uses: ./.github/workflows/docker-build.yml
    with:
      context: ./databases/mongodb
      file: ./databases/mongodb/Dockerfile
      tags: ghcr.io/sparkedhost/images:mongodb-${{ matrix.version }}
      build_args: MONGO_VERSION=${{ matrix.image }}
    secrets: inherit
