name: Build mongodb-8
on:
  push:
    branches:
      - main
    paths:
      - databases/mongodb/mongodb-8/*
      - databases/mongodb/entrypoint.sh
      - .github/workflows/mongodb-8.yml
jobs:
  push:
    name: "mongodb-8"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./databases/mongodb
          file: ./databases/mongodb/mongodb-8/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:mongodb-8
