name: Build nodejs-22
on:
  push:
    branches:
      - main
    paths:
      - nodejs/nodejs-22/*
      - nodejs/entrypoint.sh
      - .github/workflows/nodejs-22.yml
jobs:
  push:
    name: "nodejs-22"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./nodejs
          file: ./nodejs/nodejs-22/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:nodejs-22