name: Build postgres-17
on:
  push:
    branches:
      - main
    paths:
      - databases/postgres/postgres-17/*
      - databases/postgres/entrypoint.sh
      - .github/workflows/postgres-17.yml
jobs:
  push:
    name: "postgres-17"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./databases/postgres
          file: ./databases/postgres/postgres-17/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:postgres-17
