name: Build python-3.11
on:
  push:
    branches:
      - main
    paths:
      - python/python-3.11/*
      - python/entrypoint.sh
      - .github/workflows/python-3.11.yml
  workflow_dispatch:
jobs:
  push:
    name: "python-3.11"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./python
          file: ./python/python-3.11/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:python-3.11
