name: Build redis-6
on:
  push:
    branches:
      - main
    paths:
      - database/redis/redis-6/*
      - databases/redis/entrypoint.sh
      - .github/workflows/redis-6.yml
jobs:
  push:
    name: "redis-6"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.9.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./databases/redis
          file: ./databases/redis/redis-6/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sparkedhost/images:redis-6
